# ports: HOST:CONTAINER
version: '3.8'
services:
  go:
    build: .
    container_name: ${APP_NAME}-go
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - VIRTUAL_PORT=9005
    networks:
      - nproxy

networks:
  nproxy:
    external:
      name: nginx-proxy-net